// <auto-generated />
namespace INATEL_T141_DM106_Final_Homework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Order_table_creation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Order_table_creation));
        
        string IMigrationMetadata.Id
        {
            get { return "201709110145495_Order_table_creation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
